name: wavemall
description: wavemall Mobile App

publish_to: "none"

version: 2.0.9+26

environment:
  sdk: ">=3.0.0 <5.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.5.0
  share:
  http: ^1.1.0
  image_picker: ^1.0.4
  dio:
  persistent_bottom_nav_bar: ^5.0.2
  google_sign_in: ^6.1.5
  expandable: ^5.0.1
  octo_image: ^2.0.0
  animated_splash_screen: ^1.3.0
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.14
  country_code_picker: ^3.0.0
  pin_code_fields: ^8.0.1
  dotted_border: ^2.1.0
  flutter_svg: ^2.0.7
  dotted_line: ^3.2.2
  expansion_tile_card: ^3.0.0
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^3.0.0
  #  slide_countdown_clock: ^1.0.3
  flutter_animation_progress_bar: ^2.3.1
  timelines: ^0.1.0
  clipboard: ^0.1.3
  extended_nested_scroll_view: ^6.1.2
  flutter_page_view_indicator: ^0.0.5
  #  flutter_page_indicator: ^0.0.3
  #  transformer_page_view: ^0.1.6
  flutter_spinkit: ^5.2.0
  fancy_shimmer_image: ^2.0.3
  get_storage: ^2.1.1
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  flutter_cupertino_datetime_picker:
    git: https://github.com/emran92/flutter_cupertino_datetime_picker
  avatar_glow: ^2.0.2
  file_picker: ^5.5.0
  loading_skeleton_niu: ^0.0.1
  flutter_easyloading: ^3.0.5
  scratcher: ^2.4.0
  share_plus: ^7.1.0
  animate_do: ^3.1.2
  # stripe_payment: ^1.1.4
  # razorpay_flutter: ^1.3.3
  webview_flutter: ^4.2.4
  http_auth: ^1.0.3
  flutter_paystack: ^1.0.7
  flutter_webview_plugin: ^0.4.0
  flutter_inappwebview: ^5.7.2+3
  flutterwave_standard: ^1.0.8
  multi_select_flutter: ^4.1.3
  flutter_swipe: ^1.0.1
  flutter_xlider:
    git:
      url: https://github.com/swaroopsuthar/flutter_xlider.git
      ref: master
  loading_more_list: ^6.0.0
  supercharged: ^2.1.1
  pay: ^1.1.2
  flutter_staggered_grid_view: ^0.7.0
  #  photo_view:
  #    git: https://github.com/bluefireteam/photo_view.git
  photo_view: any
  #  stripe_sdk: ^5.0.0-nullsafety.0
  # stripe:
  #   path: stripe_sdk
  paytm_allinonesdk: ^1.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_html: ^3.0.0-alpha.3
  dio_http_cache: ^0.3.0
  circular_countdown_timer: ^0.2.3
  badges: ^3.1.2
  flutter_facebook_auth: ^6.0.2
  sign_in_with_apple: ^5.0.0
  flutter_polygon_clipper: ^1.0.4
  flutter_countdown_timer: ^4.1.0
  async: ^2.11.0
  group_radio_button: ^1.3.0
  #  simple_animations: ^4.2.0
  mask_text_input_formatter: ^2.5.0
  awesome_card: ^1.1.7
#  simple_animations: ^5.0.2
#  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

dependency_overrides:
  intl: ^0.17.0
  http: ^0.13.5
  flutter_slidable: ^0.6.0
  file_picker: ^5.2.6
  pay: ^1.0.10
  flutter_native_splash: ^2.2.2
  flutter_launcher_icons: ^0.9.2
  hive_generator: ^1.1.1
  build_runner: ^2.1.7

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/config/app_logo.jpg"

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#FF3364"
  image: assets/config/splash_screen_logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/config/
    - assets/fonts/
    - assets/payment/

  fonts:
    - family: CircularStdLight
      fonts:
        - asset: assets/fonts/CircularStd-Light.otf
    - family: CircularStdBlack
      fonts:
        - asset: assets/fonts/CircularStd-Black.otf
    - family: CircularStdBold
      fonts:
        - asset: assets/fonts/CircularStd-Bold.otf
    - family: CircularStdMedium
      fonts:
        - asset: assets/fonts/CircularStd-Medium.otf
    - family: CircularStdBook
      fonts:
        - asset: assets/fonts/CircularStd-Book.otf
    - family: NRT
      fonts:
        - asset: fonts/NRT-Reg.ttf
